# Generated by Django 5.0.3 on 2024-03-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safemed', '0005_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
